// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20210402185205_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SqMiles")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "Wyoming, Montana, and Idaho",
                            Name = "Yellowstone",
                            SqMiles = 3471
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "Niagara Falls, Lewiston, and Porter, New York",
                            Name = "Niagara Falls National Heritage Area",
                            SqMiles = 1
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "California",
                            Name = "Yosemite National Park",
                            SqMiles = 1169
                        },
                        new
                        {
                            ParkId = 4,
                            Location = "Montana",
                            Name = "Glacier National Park",
                            SqMiles = 1583
                        },
                        new
                        {
                            ParkId = 5,
                            Location = "Minnesota",
                            Name = "Frontenac State Park",
                            SqMiles = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
